### ISSUE TITLE
window.mochaResults not being populated

### ISSUE THREAD

**Issue by callumacrae** [pbakaus/mocha-sauce#10]
I'm getting the following error:

> TypeError: Cannot read property 'reporterOptions' of undefined

It's coming from `new mocha._reporter(runner);` [here](https://github.com/pbakaus/mocha-sauce/blob/master/client.js#L108), and I had to wrap it in a try-catch block to actually see the error: it was dying silently before.

Setting the "xunit" option to false fixed it, and now `window.mochaResults` is populated. I'm assuming it wasn't supposed to be false, though, if it was the default.

Any ideas?

**Comment by papaonlegs** [comment]
I did not run into that when I first used this, though I suspect it might be because of a newer mocha version.

Can you confirm the versions of `mocha`, `mocha-phantomjs` & `phantomjs` that you are using?

It probably makes sense to default it to false, but also figure out how to enable `xunit` on newer versions of those libs. (Maybe that + other smaller fixes could be good for a version bump of this)

**Comment by callumacrae** [comment]
I'm running mocha 2.2.4, and I'm not using mocha-phantomjs or phantomjs.

**Comment by papaonlegs** [comment]
That would do it, in [2.0.0](https://github.com/mochajs/mocha/compare/2.0.0...master) they introduced a __mandatory__ [`options`](https://github.com/mochajs/mocha/commit/82bba0cd9c38e9a779eba544552cee714154c6c2).

I'll put a PR in for that, in the meantime you can downgrade to 1.9 as in the [readme](https://github.com/pbakaus/mocha-sauce#dependencies)

**Comment by papaonlegs** [comment]
@callumacrae see attached PR, feel free to pull & test

**Comment by papaonlegs** [comment]
@callumacrae Should be good now

**Comment by callumacrae** [comment]
Thanks! :clap: 

Any ETA on a release on npm?

**Comment by papaonlegs** [comment]
I've emailed the guy who published [this](https://www.npmjs.com/package/mocha-sauce) and CC'ed npm supprt, last week, to get added as a collaborator there so I can publish there.

Still waiting for the forbes guy to reply.
